import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"
import Layout from "../components/layout/Layout";
const myFont = localFont({
  src: "../font/Vazirmatn-Regular.woff2",
});
export const metadata: Metadata = {
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${myFont.className} antialiased bg-gray-100`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
